// Code generated by protoc-gen-go.
// source: pb/calculator.proto
// DO NOT EDIT!

/*
Package network is a generated protocol buffer package.

It is generated from these files:
	pb/calculator.proto

It has these top-level messages:
	Request
	Response
*/
package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Expression string `protobuf:"bytes,2,opt,name=expression" json:"expression,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Error  string  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Result float64 `protobuf:"fixed64,3,opt,name=result" json:"result,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
